spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1/sell?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 127.0.0.1
    port: 6379
server:
  port: 8089
  servlet:
    context-path: /sell

# 下面是微信相关的配置
wechat:
#  mpAppId: wxdcf91e9f784bfad0
#  mpAppSecret: c467c06d98a2447f5ddef6ca8f47f268 #测试号appId,appSecret
  mp-app-id: wxd898fcb01713c658
  mp-appsecret: xxxxxxxxx #借用号appId,appSecret
#  openAppId: wx6ad144e54af67d87
#  openAppSecret: 91a2ff6d38a2bbccfb7e9f9079108e2e #开放平台测试号appId,appSecret
  open-app-id: wx6ad144e54af67d87
  open-app-secret: 91a2ff6d38a2bbccfb7e9f9079108e2e #借用帐号appId,appSecret
  mch-id: 1483469312
  mch-key: C5245D70627C1F8E9964D494B0735025
  key-path: C:/Users/Administrator/Downloads/h5.p12
  notify-url: http://sqmax.natapp1.cc/notify
  template-id:
    order-status: GoCullfix05R-rCibvoyI87ZUg50cyieKA5AyX7pPzo

project-url:
  wechat-mp-authorize: http://sqmax.natapp1.cc
  wechat-open-authorize: http://sqmax.natapp1.cc
  sell: http://sqmax.natapp1.cc
mybatis-plus:
  configuration:
    auto-mapping-unknown-column-behavior: warning
#    log-impl: org.apache.ibatis.logging.slf4j.Slf4jLoggerImpl
  global-config:
    refresh: true

# 打印sql日志
logging:
  level:
    com.imooc.mapper: debug
    com.baomidou.mybatisplus.core.mapper: debug
alipay:
  return-url: http://5gkhgq.natappfree.cc
  notify-url: http://5gkhgq.natappfree.cc
  serve-url: https://openapi.alipaydev.com/gateway.do
  app-id: 2016092000558410
  format: json
  charset: utf-8
  private-key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQClGRvC5Cfu1fhDwPWYw9H0qbFitkxJ3rpfnvR70IXYfoHM/AmVAGSyajs85GQFckIdvnAxkPGugiHueraALmCXybKAi2A2CwMDLZSPnbTbh9ylmYWG7snDU2l5YlF7/XInp/3PZThhpJvyEqekIq0vu+7ZXM0otXQ0Rzf6KQkkxAAg4SXDi6XeG84i1NcN7orYUzFWB3avES/M/ksVG994PPjZbnvflOdURqajZV+lGMGzD32mnHuRX0jrR1H4mXPLai11TVVwGDRpw0Mo8SoW0kDyRRtFAgpfU18Dtpt0lKdA5HV5gmgFbR/AAm4t2GbrdMSjigyBtUoZnnPiWUUBAgMBAAECggEAZsYrlvXque3u/1Z2TKPR5mlgaF+tO+rvwCi2bwEO4QdXjCB1YpD9Hmes+qn+bbmD2Po8404kdQrDTq6LP14feT3w5b5dpSbTuD2+lmyJMoPv4hKgoa+yX+pj5VFEAlhyoKceA+Yx4+7RuS7NtwpzHxzxgdQYTrguX4DaIts6uuxaOW2BBSU5AEh71JeBKaTAmWAdEdOylAAlsZ1R5k8r995pCCKieLP0c4NXLvnPalsOW+zfJosf8u7yNQ35rqGW0siDfw3bL22esheGF9z+bVN1C/jIVvrYZYD3oxkH9mP4AFiKY+Tr5iVx2Bzd4txl8h6ww+ygEvSA/YYK+DFEwQKBgQDqNGkStPvu0sCddAZkyD4V2ws2mWfl3ZOLvNj6neJ6S3uyFjCwGzb7WuBjcGFZRLes7NwD5KBlUbaT8YlhlDbV1zdSlInICxUj18oLp5TbOW6Is0lhvmTQTF8veDLTvuVsHrc+bpxENH565M7o4QHRnz1z/b8uxZw2MV80wsVCKQKBgQC0dlT09t2WJDom19yJBJ/oisvOuXsjDvSypC2zYv5FTDce+dXymcnc5Hx9h4iJjCTpiJRUTl3cRH9neS964hpB6QiKhf6ESBKx5S88pF/WzCjAYC3Q25BF4ASDJvxL/V7FVngFReaMkFXi2XcDqTQ5zi3lov3JnRIk7libXsc3GQKBgAhxyVQWWHsc+Dr1IwHhQnPRSQ836sob+iTwszYeGTtlm1kpeanv4USg2zRaqffpBWJjy+8MAEiG8LlW3Sg6ituc/e6pUmp3E9UOA8f1y+U3peeh50Rx8/qatlfk0phV6rnCRcMng9Tlu6W8uEUnT8R6JGIZRRpvn5lIoHErkKc5AoGALe1bq8hUFoz7u7z+JGTn6X/BZMgxvXdl8Tz1YI0WFz7RXHHK8GYRSMVhpXTj29Wt4z1eOqKDIrbQEd52pfh7JEERame1oabSEzI3tmBC/+CPkn4nytrGOfJMU7CNTy2Ze/GItBbZGPb21LfxoR3j6748UhAMNM5jusBqDoitfKkCgYEA3KFFq8B9NLUyQH/rDNCKg79xRZiD2kxZQjoVCC2cl7at0bKordygtlUgCF4rdMiai3ZIwOgTeQU4A2PnfnyMHUn949BDmS+1AOTY6JEE3oKdCSZk1N9fWgAmaw5vxpnsqy9eFpWNfE41zaC8GwPgZliFhUf6p9IvwrdfKfN8TWg=
  alipay-public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAyHCoUb71+nte1nsQM9gApxjBqO+Jrd4rm6OTwh0aSobtWZHoiLlOB7/LYRmU7a7UEmsQ05DKWjkpEntr9EymhKxa2t4hkLZnAoByXiYLZ46bHq+4DCkIyYuuFsXbWBpu+nE2BKzf7Q1baOv8Z00Fpa9jy2OW1KC0hh2FANvbAJ8+HFwzAw+ZT0/tmoDs2fXZxM7I7HjkvakwmbTxzxRSlNjt7akhDti3CZ0Hy0EyruWgj995WdcR+xJY39M0kDD6NEBfC9qm7o5spI6R8l+u5hg/7si/8H4QyluoBh+XpMZJ9ee+BZjb1qx86IyttyW+pkS8AeUQTu1MZYVSySOBqwIDAQAB
  sign-type: RSA2


