spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1/sell?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 127.0.0.1
    port: 6379
server:
  port: 8089
  servlet:
    context-path: /sell

# 下面是微信相关的配置
wechat:
#  mpAppId: wxdcf91e9f784bfad0
#  mpAppSecret: c467c06d98a2447f5ddef6ca8f47f268 #测试号appId,appSecret
  mp-app-id: wxd898fcb01713c658
  mp-appsecret: xxxxxxxxx #借用号appId,appSecret
#  openAppId: wx6ad144e54af67d87
#  openAppSecret: 91a2ff6d38a2bbccfb7e9f9079108e2e #开放平台测试号appId,appSecret
  open-app-id: wx6ad144e54af67d87
  open-app-secret: 91a2ff6d38a2bbccfb7e9f9079108e2e #借用帐号appId,appSecret
  mch-id: 1483469312
  mch-key: C5245D70627C1F8E9964D494B0735025
  key-path: C:/Users/Administrator/Downloads/h5.p12
  notify-url: http://sqmax.natapp1.cc/notify
  template-id:
    order-status: GoCullfix05R-rCibvoyI87ZUg50cyieKA5AyX7pPzo

project-url:
  wechat-mp-authorize: http://sqmax.natapp1.cc
  wechat-open-authorize: http://sqmax.natapp1.cc
  sell: http://sqmax.natapp1.cc
mybatis-plus:
  configuration:
    auto-mapping-unknown-column-behavior: warning
#    log-impl: org.apache.ibatis.logging.slf4j.Slf4jLoggerImpl
  global-config:
    refresh: true

# 打印sql日志
logging:
  level:
    com.imooc.mapper: debug
